In [2]:
import torch
import numpy as np


In [11]:
# x = torch.tensor(5)
# x = torch.tensor([10, 20, 30])
# x = torch.tensor([
#     [1, 2, 3],
#     [4, 5, 6]
# ])
x = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(x)
print(x.ndim)
print(x.shape)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3
torch.Size([2, 2, 3])


In [10]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)
print(x.ndim)
print(x.shape)


[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [3]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [5, 6],
    [7, 8]
])

In [5]:
a@b

tensor([[19, 22],
        [43, 50]])

In [8]:
a.mm(b)

tensor([[19, 22],
        [43, 50]])

In [9]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)
print(a * b)



tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [ ]:
a = torch.tensor([
    [1, 2],
    [3, 4]
])

b = torch.tensor([
    [10, 20],
    [30, 40]
])

print(a * b)


In [42]:
m1 = torch.randint(0,100,size=(2,3))
m2 = torch.randint(0,100,size=(2,1))


In [29]:
m1

tensor([[30, 48,  8],
        [86, 45, 48]])

In [30]:
m2

tensor([[ 2, 99, 93, 72],
        [67, 65, 88, 33]])

In [40]:
print(m1@m2)

tensor([[10026,  2880,  5596,  4856,  3972,  8148,  2136,  3432,  3758,  8540],
        [ 5574,  1224,  2714,  2393,  2229,  4279,  1009,  1434,  1588,  4538]])


In [43]:
s = m1 / m2
print(s.shape)

torch.Size([2, 3])


In [44]:
s

tensor([[0.3333, 3.3810, 0.3810],
        [2.0000, 1.1176, 1.7059]])

In [3]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
x.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
x = torch.tensor([1, 2, 3])
print(x.unsqueeze(2))

tensor([[1],
        [2],
        [3]])
