# Importing PyTorch

In [1]:
import torch
print("PyTorch Version: ", torch.__version__)

PyTorch Version:  2.6.0+cu124


# Creating Tensors

###### **Scalar**

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
print('Type: ', type(scalar))
print('Shape: ', scalar.shape)
print('Dimension: ', scalar.ndim)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([])
Dimension:  0


In [4]:
integer = scalar.item()
print('Extract the value: ', integer)
print('Type: ', type(integer))

Extract the value:  7
Type:  <class 'int'>


###### **Vector**

In [5]:
vector = torch.tensor([2, 5, 8])
vector

tensor([2, 5, 8])

In [6]:
print('Shape: ', vector.shape)
print('Dimension: ', vector.ndim)

Shape:  torch.Size([3])
Dimension:  1


###### **Matrix**

In [7]:
matrix = torch.tensor([
                       [1, 2, 3],
                       [4, 5, 6]
                      ])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
print('Shape: ', matrix.shape)
print('Dimension: ', matrix.ndim)

Shape:  torch.Size([2, 3])
Dimension:  2


In [9]:
my_tensor = torch.tensor([
                        [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]]
                        ])
my_tensor

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [10]:
print('Shape: ', my_tensor.shape)
print('Dimension: ', my_tensor.ndim)

Shape:  torch.Size([1, 3, 4])
Dimension:  3


In [11]:
# Add another tensor at dim 1

my_tensor = torch.tensor([
                        [
                        [1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]]
                        ,
                        [
                        [1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]
                        ]
                        ])
my_tensor

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]])

In [12]:
print('Shape: ', my_tensor.shape)
print('Dimension: ', my_tensor.ndim)

Shape:  torch.Size([2, 3, 4])
Dimension:  3


##### **Random**

In [13]:
random_tensor = torch.rand(size=(3, 4)) # Returns a tensor filled with random numbers from a uniform distribution on the interval [0,1)
random_tensor, random_tensor.dtype

(tensor([[0.6991, 0.9509, 0.7431, 0.2474],
         [0.8587, 0.5047, 0.4038, 0.0252],
         [0.3731, 0.0271, 0.6305, 0.0444]]),
 torch.float32)

In [14]:
random_tensor = torch.randint(low=7, high=15, size=(2, 2))
random_tensor

tensor([[13, 11],
        [ 9, 14]])

In [15]:
random_image = torch.rand(size=(128, 128, 3))

print('Shape: ', random_image.shape)
print('Dimension: ', random_image.ndim)

Shape:  torch.Size([128, 128, 3])
Dimension:  3


In [16]:
random_tensor = torch.randn([3, 5])
random_tensor

tensor([[-1.2995, -0.4057,  1.7455, -1.5444, -0.9246],
        [-0.3471, -1.7603, -0.4202,  0.5111,  0.3122],
        [-1.5612, -0.4646,  1.3946, -1.3201, -0.2683]])

##### **Zeros and Ones**

In [17]:
zeros = torch.zeros(size=(3, 4))
print("Zeros: ", zeros)

print()

ones = torch.ones(size=(3, 4))
print("Ones: ", ones)

Zeros:  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


##### **Range**

In [18]:
ranges = torch.arange(start=0, end=10, step=2)
ranges

tensor([0, 2, 4, 6, 8])

##### **More Precise Tensor Creation**

In [19]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.2, 6.4, 1000.7],
                               dtype=torch.float32,
                               device='cpu',
                               requires_grad=False)

print('Shape: ', float_32_tensor.shape)
print('Dimension: ', float_32_tensor.ndim)
print('Datatype: ', float_32_tensor.dtype)
print('Device: ', float_32_tensor.device)

Shape:  torch.Size([3])
Dimension:  1
Datatype:  torch.float32
Device:  cpu


###### **to()**

In [20]:
new_tensor = float_32_tensor.to(torch.int8)
print('Datatype: ', new_tensor.dtype)
print('Values: ', new_tensor)

Datatype:  torch.int8
Values:  tensor([  3,   6, -24], dtype=torch.int8)


In [21]:
# stack to()
new_tensor.to(torch.float16).to('cpu')

tensor([  3.,   6., -24.], dtype=torch.float16)

###### **Moving tensor to GPU**

In [22]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [23]:
# Move tensor to GPU (if available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

###### **Moving tensors back to the CPU**

In [24]:
"""
What if we wanted to move the tensor back to CPU?
For example, you'll want to do this if you want to interact with your tensors with NumPy (NumPy does not leverage the GPU).
"""

try:
    tensor = tensor_on_gpu.numpy()
except Exception as err:
    print('Error:', err)

In [25]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

##### **Alternative ways to convert data to tensor**

In [26]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)

###### **1. torch.from_numpy**

In [27]:
# 1. torch.from_numpy() |--> shares memory with np_array, so changes in np_array reflect in tensor_from_numpy
tensor_from_numpy = torch.from_numpy(np_array)

print("Original NumPy array:", np_array)
print("torch.from_numpy:", tensor_from_numpy)

Original NumPy array: [1. 2. 3. 4. 5.]
torch.from_numpy: tensor([1., 2., 3., 4., 5.], dtype=torch.float64)


In [28]:
np_array[0] = 10 # Modify the NumPy array
print("Modified NumPy array:", np_array)
print("torch.from_numpy:", tensor_from_numpy)

Modified NumPy array: [10.  2.  3.  4.  5.]
torch.from_numpy: tensor([10.,  2.,  3.,  4.,  5.], dtype=torch.float64)


###### **2. torch.as_tensor**

In [29]:
# 2. torch.as_tensor() |--> Copies if NumPy but If already a tensor, no copy is made.
# 2.1 --> input is NumPy array
np_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)

tensor_as_tensor = torch.as_tensor(np_array)
print("Original NumPy array:", np_array)
print("torch.as_tensor:", tensor_as_tensor)

Original NumPy array: [1. 2. 3. 4. 5.]
torch.as_tensor: tensor([1., 2., 3., 4., 5.], dtype=torch.float64)


In [30]:
np_array[1] = 20
print("Modified NumPy array:", np_array)
print("Tensor after modifying NumPy array:", tensor_as_tensor)

Modified NumPy array: [ 1. 20.  3.  4.  5.]
Tensor after modifying NumPy array: tensor([ 1., 20.,  3.,  4.,  5.], dtype=torch.float64)


In [31]:
# 2.2 --> input is Tensor with same dtype
input_tensor = torch.arange(0, 5, dtype=torch.int16)
tensor_as_tensor = torch.as_tensor(input_tensor)

tensor_as_tensor[-2] = 50
print("Input Tensor:", input_tensor)
print("Tensor after modifying:", tensor_as_tensor)

Input Tensor: tensor([ 0,  1,  2, 50,  4], dtype=torch.int16)
Tensor after modifying: tensor([ 0,  1,  2, 50,  4], dtype=torch.int16)


In [32]:
# 2.3 --> input is Tensor with different dtype
input_tensor = torch.arange(0, 5, dtype=torch.int16)
tensor_as_tensor = torch.as_tensor(input_tensor, dtype=torch.float64)

tensor_as_tensor[-2] = 50
print("Input Tensor:", input_tensor)
print("Tensor after modifying:", tensor_as_tensor)

Input Tensor: tensor([0, 1, 2, 3, 4], dtype=torch.int16)
Tensor after modifying: tensor([ 0.,  1.,  2., 50.,  4.], dtype=torch.float64)


In [33]:
# 2.4 --> input is List
list_data = [1, 2, 3, 4, 5]
tensor = torch.as_tensor(list_data)

# Modify the list
list_data[0] = 10
print("Modified list:", list_data)
print("Tensor after modifying list:", tensor)

Modified list: [10, 2, 3, 4, 5]
Tensor after modifying list: tensor([1, 2, 3, 4, 5])


###### **3. torch.tensor**

In [34]:
# 3. torch.tensor() |--> Always creates a new tensor and does not share memory with the source data; a new copy is made.
np_array = np.array([1, 2, 3, 4, 5])

tensor_np_array = torch.tensor(np_array)
list_data = [1, 2, 3, 4, 5]
tensor_from_list = torch.tensor(list_data)

In [35]:
tensor_np_array[-2] = 100
print("Original NumPy array:", np_array)
print("Tensor after modifying:", tensor_np_array)

Original NumPy array: [1 2 3 4 5]
Tensor after modifying: tensor([  1,   2,   3, 100,   5])


In [36]:
list_data[-2] = 100

print("Original list:", list_data)
print("Tensor after modifying:", tensor_from_list)

Original list: [1, 2, 3, 100, 5]
Tensor after modifying: tensor([1, 2, 3, 4, 5])


# Tensor Operations

##### **Basic Operations**

In [37]:
my_tensor = torch.tensor([1, 2, 3])

In [38]:
my_tensor + 10

tensor([11, 12, 13])

In [39]:
torch.add(my_tensor, 10) # add = addition

tensor([11, 12, 13])

In [40]:
my_tensor - 5

tensor([-4, -3, -2])

In [41]:
my_tensor * 10

tensor([10, 20, 30])

In [42]:
torch.mul(my_tensor, 10) # mul = multiplication

tensor([10, 20, 30])

In [43]:
my_tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [44]:
# Attention: the values inside the tensor don not change unless they're reassigned.
my_tensor

tensor([1, 2, 3])

In [45]:
my_tensor = my_tensor + 1
my_tensor

tensor([2, 3, 4])

In [46]:
my_tensor -= 1
my_tensor

tensor([1, 2, 3])

##### **Automatic differentiation**

The most important advantage of PyTorch over NumPy is its automatic differentiation functionality which is very useful in optimization applications such as optimizing parameters of a neural network. Let's try to understand it with an example.

Say you have a composite function which is a chain of two functions: `g(u(x))`.
To compute the derivative of `g` with respect to `x` we can use the chain rule which states that: `dg/dx = dg/du * du/dx`. PyTorch can analytically compute the derivatives for us.

To compute the derivatives in PyTorch first we create a tensor and set its `requires_grad` to true. We can use tensor operations to define our functions. We assume `u` is a quadratic function and `g` is a simple linear function:

In [47]:
x = torch.tensor(1.0, requires_grad=True)

def u(x):
  return x * x

def g(u):
  return -u

In this case our composite function is `g(u(x)) = -x*x`. So its derivative with respect to `x` is `-2x`. At point `x=1`, this is equal to `-2`.

Let's verify this. This can be done using grad function in PyTorch:

In [48]:
dgdx = torch.autograd.grad(g(u(x)), x)[0]
print(dgdx)  # tensor(-2.)

tensor(-2.)


##### **Matrix Multiplication**

In [49]:
# Matrix multiplication functionality is in the torch.matmul() method.

my_tensor = torch.tensor([1, 2, 3])

print("Element-wise multiplication:", my_tensor * my_tensor, "| Math: [1*1, 2*2, 3*3] = [1, 4, 9]")
print()
print("Matrix multiplication:", torch.matmul(my_tensor, my_tensor), "| Math: [1*1 + 2*2 + 3*3] = [14]")

Element-wise multiplication: tensor([1, 4, 9]) | Math: [1*1, 2*2, 3*3] = [1, 4, 9]

Matrix multiplication: tensor(14) | Math: [1*1 + 2*2 + 3*3] = [14]


In [50]:
tensor_a = torch.rand(4, 8)
tensor_b = torch.rand(8, 4)

print("Shapes:")
print("tensor_a:", tensor_a.shape, "|", "tensor_b:", tensor_b.shape)

Shapes:
tensor_a: torch.Size([4, 8]) | tensor_b: torch.Size([8, 4])


In [51]:
matrix_multiplication = torch.matmul(tensor_a, tensor_b)
print('Input Shape: ', tensor_a.shape, '|', tensor_b.shape)
print('Output Shape: ', matrix_multiplication.shape)

Input Shape:  torch.Size([4, 8]) | torch.Size([8, 4])
Output Shape:  torch.Size([4, 4])


In [52]:
matrix_multiplication = torch.matmul(tensor_b, tensor_a)
print('Input Shape: ', tensor_b.shape, '|', tensor_a.shape)
print('Output Shape: ', matrix_multiplication.shape)

Input Shape:  torch.Size([8, 4]) | torch.Size([4, 8])
Output Shape:  torch.Size([8, 8])


In [53]:
try:
  torch.matmul(tensor_a, tensor_a)
except Exception as err:
  print("Error: ", err)
  print()
  print('Input Shape: ', tensor_a.shape, '|', tensor_a.shape)

Error:  mat1 and mat2 shapes cannot be multiplied (4x8 and 4x8)

Input Shape:  torch.Size([4, 8]) | torch.Size([4, 8])


In [54]:
# One way to solve a shape mismatch is by using a transpose operation (switching the dimensions of a given tensor).

print('Shape of transpose of tensor_a: ', tensor_a.T.shape)
print()

transpose = tensor_a.T
torch.matmul(tensor_a, transpose)

Shape of transpose of tensor_a:  torch.Size([8, 4])



tensor([[2.0590, 1.4355, 2.0669, 2.1937],
        [1.4355, 2.5937, 1.5273, 2.0232],
        [2.0669, 1.5273, 2.3065, 2.3539],
        [2.1937, 2.0232, 2.3539, 3.2706]])

In [55]:
# Other shortcuts for torch.matmul

a = tensor_a.matmul(transpose)
b = torch.mm(tensor_a, transpose)

a == b

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

##### **min, max, mean, sum**

In [56]:
x = torch.arange(-50, 60, 10)
x

tensor([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40,  50])

In [57]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")

Minimum: -50
Maximum: 50
Sum: 0


In [58]:
try:
  print(f"Mean: {x.mean()}")
except Exception as err:
  print("Error: ", err)

Error:  mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [59]:
x_float = x.to(torch.float32)
print(f"Mean: {x_float.mean()}")

Mean: 0.0


In [60]:
# Alternative
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(50), tensor(-50), tensor(0.), tensor(0))

In [61]:
print(f"Tensor: {x}")

# Returns index of max and min values
print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Tensor: tensor([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40,  50])
Index where max value occurs: 10
Index where min value occurs: 0


##### **Reshaping, stacking, concating, squeezing and unsqueezing**

###### **Reshape**

In [68]:
x = torch.arange(0, 11, 2)
print(f'Values: {x} | Shape: {x.shape}')

Values: tensor([ 0,  2,  4,  6,  8, 10]) | Shape: torch.Size([6])


In [69]:
z = x.reshape(1, -1) # add an extra dimension

print(f'Values X: {x} | Shape X: {x.shape}')
print(f'Values Z: {z} | Shape Z: {z.shape}')

Values X: tensor([ 0,  2,  4,  6,  8, 10]) | Shape X: torch.Size([6])
Values Z: tensor([[ 0,  2,  4,  6,  8, 10]]) | Shape Z: torch.Size([1, 6])


In [70]:
z[0, 2] = 100

print(f'Values X: {x} | Shape X: {x.shape}')
print(f'Values Z: {z} | Shape Z: {z.shape}')

Values X: tensor([  0,   2, 100,   6,   8,  10]) | Shape X: torch.Size([6])
Values Z: tensor([[  0,   2, 100,   6,   8,  10]]) | Shape Z: torch.Size([1, 6])


In [71]:
print('reshape: ', x.reshape(2,3).shape)
print('view: ', x.view(2,3).shape)

reshape:  torch.Size([2, 3])
view:  torch.Size([2, 3])


In [75]:
print(f'z shape: {z.shape}')


z shape: torch.Size([1, 6])


###### **Unsqueeze**

In [77]:
z = z.unsqueeze(0)
print(f'z shape: {z.shape}')

z shape: torch.Size([1, 1, 1, 6])


In [78]:
z = z.unsqueeze(-1)
print(f'z shape: {z.shape}')

z shape: torch.Size([1, 1, 1, 6, 1])


###### **Squeeze**

In [79]:
# Squeeze last dimension only
print('Squeezed shape: ', z.squeeze(-1).shape)

Squeezed shape:  torch.Size([1, 1, 1, 6])


In [80]:
# Squeeze all dims
print('Squeezed shape: ', z.squeeze().shape)

Squeezed shape:  torch.Size([6])


###### **Stacking**

In [81]:
x = torch.arange(0, 6, 1)
print(f'x value: {x}, | x shape: {x.shape}')

x value: tensor([0, 1, 2, 3, 4, 5]), | x shape: torch.Size([6])


In [82]:
# Stack tensors on top of each other
stacked = torch.stack([x, x, x], dim=0) # dim = 0
print(f'stacked value:\n {stacked}')
print()
print(f'stacked shape: {stacked.shape}')

stacked value:
 tensor([[0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5],
        [0, 1, 2, 3, 4, 5]])

stacked shape: torch.Size([3, 6])


In [83]:
# Stack tensors on top of each other
stacked = torch.stack([x, x, x], dim=1) # dim = 1
print(f'stacked value:\n {stacked}')
print()
print(f'stacked shape: {stacked.shape}')

stacked value:
 tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

stacked shape: torch.Size([6, 3])


###### **Concatenation**

In [84]:
x = torch.arange(0, 6, 1)
print(f'x value: {x}, | x shape: {x.shape}')

x value: tensor([0, 1, 2, 3, 4, 5]), | x shape: torch.Size([6])


In [85]:
concat = torch.cat([x, x, x], dim=0) # dim = 0
print(f'concat value:\n {concat}')
print()
print(f'concat shape: {concat.shape}')

concat value:
 tensor([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

concat shape: torch.Size([18])


In [88]:
try:
    concat = torch.cat([x, x, x], dim=1) # dim = 1
except Exception as err:
    print("Error: ", err)
    print("x shape: ", x.shape)

Error:  Dimension out of range (expected to be in range of [-1, 0], but got 1)
x shape:  torch.Size([6])


In [90]:
y = x.unsqueeze(1)
y.shape

torch.Size([6, 1])

In [91]:
concat = torch.cat([y, y, y], dim=1) # dim = 1
print(f'concat value:\n {concat}')
print()
print(f'concat shape: {concat.shape}')
print('Same as stacking on dim 1!')

concat value:
 tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5]])

concat shape: torch.Size([6, 3])
Same as stacking on dim 1!


###### **Permutation**

In [102]:
x = torch.rand(size=(256, 128, 3))

x_permuted = x.permute(2, 0, 1)

print(f"Before: {x.shape}")
print(f"After:  {x_permuted.shape}")

Before: torch.Size([256, 128, 3])
After:  torch.Size([3, 256, 128])


# Indexing

In [105]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [106]:
print("Original Shape: ", x.shape)
print()
print("First bracket:\n", x[0], f'Shape: {x[0].shape}')
print()
print("Second bracket:", x[0][0], f'Shape: {x[0][0].shape}')
print()
print("Third bracket:", x[0][0][0], f'Shape: {x[0][0][0].shape}')

Original Shape:  torch.Size([1, 3, 3])

First bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) Shape: torch.Size([3, 3])

Second bracket: tensor([1, 2, 3]) Shape: torch.Size([3])

Third bracket: tensor(1) Shape: torch.Size([])


In [109]:
x[:, 0] == x[0, 0]

tensor([[True, True, True]])

In [112]:
# Why? Because:
print(x, x.shape)
print()
print(x[:, 0])
print()
print(x[0, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])

tensor([[1, 2, 3]])

tensor([1, 2, 3])


In [113]:
x[:, 1]

tensor([[4, 5, 6]])

In [114]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [117]:
x[:, 1, 1]

tensor([5])

Indexing can be quite confusing to begin with, especially with larger tensors (I still have to try indexing multiple times to get it right).

# PyTorch & NumPy

In [118]:
import numpy as np

array = np.arange(1.0, 8.0, dtype=np.float16)
tensor = torch.from_numpy(array)

print(f'Array: {array}')
print(f'Tensor: {tensor}')

Array: [1. 2. 3. 4. 5. 6. 7.]
Tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float16)


In [119]:
tensor = torch.rand(3, dtype=torch.float16)
numpy_tensor = tensor.numpy()

print(f'Tensor: {tensor}')
print(f'Array: {numpy_tensor}, dtype: {numpy_tensor.dtype}')

Tensor: tensor([0.3242, 0.6416, 0.1963], dtype=torch.float16)
Array: [0.3242 0.6416 0.1963], dtype: float16


# Seeding (Reproducibility)

###### **With Numpy**

In [133]:
def random_number_generator(seed=None):
    if seed:
        np.random.seed(seed=123)

    random_list = []
    for i in range(6):
        random_number = np.float16(np.random.rand())
        random_list.append(random_number)

    return random_list

print('List A: ', random_number_generator())
print('List B: ', random_number_generator())
print('List C: ', random_number_generator())

List A:  [np.float16(0.895), np.float16(0.7236), np.float16(0.2712), np.float16(0.2065), np.float16(0.877), np.float16(0.5884)]
List B:  [np.float16(0.01715), np.float16(0.01331), np.float16(0.371), np.float16(0.46), np.float16(0.2695), np.float16(0.0957)]
List C:  [np.float16(0.7324), np.float16(0.856), np.float16(0.9526), np.float16(0.782), np.float16(0.4097), np.float16(0.4907)]


In [134]:
# Repeat the same process with seeding
my_seed = 123

print('List A: ', random_number_generator(seed=my_seed))
print('List B: ', random_number_generator(seed=my_seed))
print('List C: ', random_number_generator(seed=my_seed))

List A:  [np.float16(0.6963), np.float16(0.2861), np.float16(0.2268), np.float16(0.5513), np.float16(0.719), np.float16(0.423)]
List B:  [np.float16(0.6963), np.float16(0.2861), np.float16(0.2268), np.float16(0.5513), np.float16(0.719), np.float16(0.423)]
List C:  [np.float16(0.6963), np.float16(0.2861), np.float16(0.2268), np.float16(0.5513), np.float16(0.719), np.float16(0.423)]


###### **With Torch**

In [137]:
def random_torch(seed):
    torch.random.manual_seed(seed)
    random_tensor = torch.rand(3, 4)

    return random_tensor

Tensor_A = random_torch(seed=my_seed)
Tensor_B = random_torch(seed=my_seed)

print('Tensor A:\n', Tensor_A)
print()
print('Tensor B:\n', Tensor_B)
print()
print(f"Does Tensor A equal Tensor B?")
print(Tensor_A == Tensor_B)

Tensor A:
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

Tensor B:
 tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

Does Tensor A equal Tensor B?
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
