In [9]:
import torch
import numpy as np

In [13]:
torch.manual_seed(42)
torch.cuda.manual_seed(555)
tens = torch.randint(0,100,size=(7,7),device="cuda").float()
tens

tensor([[83., 32., 58., 50., 29., 77., 56.],
        [39., 48., 42., 12., 41., 75., 49.],
        [72.,  4., 24., 74., 66., 78., 41.],
        [60., 21., 51., 43., 19., 48., 10.],
        [66., 36., 80., 37., 59., 14., 97.],
        [14., 40., 92., 20., 39., 58., 24.],
        [41., 34., 49.,  1., 68., 51., 19.]], device='cuda:0')

In [14]:
tens_sec = torch.randint(0,100,size=(7,1),device="cuda").float()
tens_sec_T = torch.transpose(tens_sec,0,1)
print(tens_sec.shape)
print(tens_sec_T.shape)

torch.Size([7, 1])
torch.Size([1, 7])


In [15]:
print(tens@tens_sec)

tensor([[21785.],
        [19430.],
        [20093.],
        [13212.],
        [20360.],
        [16900.],
        [15911.]], device='cuda:0')


In [16]:
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("PyTorch is using CPU")
    

PyTorch: 2.13.0+cu130
CUDA available: True
GPU: NVIDIA GeForce RTX 3060
CUDA version: 13.0


In [17]:
tesns1 = torch.rand(size=(2,3),device="cuda")
tesns2 = torch.rand(size=(2,3),device="cuda")
tesns2_prime = torch.transpose(tesns2,0,1)
print(tesns1)
print(tesns2)
print(tesns2_prime)

tensor([[0.2361, 0.8683, 0.3760],
        [0.8909, 0.4351, 0.6372]], device='cuda:0')
tensor([[0.6355, 0.8555, 0.5246],
        [0.1964, 0.7187, 0.9938]], device='cuda:0')
tensor([[0.6355, 0.1964],
        [0.8555, 0.7187],
        [0.5246, 0.9938]], device='cuda:0')


In [19]:
mat_tesns = tesns1@tesns2_prime
print(mat_tesns)

tensor([[1.0901, 1.0441],
        [1.2727, 1.1210]], device='cuda:0')


In [ ]:
#7 MinMax
print("Max : ",torch.max(mat_tesns))
print("Min : ",torch.min(mat_tesns))


Max :  tensor(1.2727, device='cuda:0')
Min :  tensor(1.0441, device='cuda:0')


In [22]:
#8 argmax and argmin
arg_max = torch.argmax(mat_tesns)
arg_min = torch.argmin(mat_tesns)
print(arg_max,arg_min)

tensor(2, device='cuda:0') tensor(1, device='cuda:0')


In [25]:
torch.cuda.manual_seed(9)
new_tens = torch.rand(size=(1,2,1,3),device="cuda")
print(new_tens.shape)

torch.Size([1, 2, 1, 3])


In [27]:
new_tens = torch.squeeze(new_tens)
new_tens.shape

torch.Size([2, 3])